spring.application.name=SaferideBackend
server.port=8086

# --- Email Notification Configurations ---
# Replace with valid credentials to send actual emails.
# For Gmail, you need to use an "App Password" rather than your regular password.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codexsaferide@gmail.com
spring.mail.password=####
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
