spring.application.name=safe-ride-backend
spring.datasource.url=jdbc:mysql://localhost:3306/saferide_db
spring.datasource.username=root
spring.datasource.password=vinuT@04
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
