spring.application.name=SaferideBackend
server.port=8085
server.address=0.0.0.0
firebase.api.key=AIzaSyD9PHGzW-pNqsB0zUHQSL_0hE3CiGzTkLw

# --- Email Notification Configurations ---
# Replace with valid credentials to send actual emails.
# For Gmail, you need to use an "App Password" rather than your regular password.
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codexsaferide@gmail.com
spring.mail.password=nnetjpajhhjixmse
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false